# AUTOGENERATED! DO NOT EDIT! File to edit: 27_Read_Varibench.ipynb (unless otherwise specified).

__all__ = ['getSequence']

# Cell
import pandas as pd
from easydict import EasyDict
import numpy as np
import ensembl_rest
from tqdm.notebook import tqdm
def getSequence(gene):
    "Get the protein sequence coded by the given gene"
    q = ensembl_rest.symbol_lookup(
        species='homo sapiens',
        symbol=gene,params={'expand':True})
    try:
        is_canonical = [t["is_canonical"] for t in q["Transcript"]]
        t = q["Transcript"][np.argmax(is_canonical)]
        seq = ensembl_rest.sequence_id(t["Translation"]["id"])["seq"]
        return seq
    except:
        return ""