# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"getBag": "02_SyntheticData.ipynb",
         "buildDatasetDict": "02_SyntheticData.ipynb",
         "Dataset": "02_SyntheticData.ipynb",
         "buildDataset": "02_SyntheticData.ipynb",
         "estimator": "03_Dataset_Utils.ipynb",
         "getBootstrapSample": "03_Dataset_Utils.ipynb",
         "getEsts": "03_Dataset_Utils.ipynb",
         "getBagAlphaHats": "03_Dataset_Utils.ipynb",
         "getCliqueAlphaHats": "03_Dataset_Utils.ipynb",
         "getAlphaPrime": "03_Dataset_Utils.ipynb",
         "getKSMatrixPMatrix": "03_Dataset_Utils.ipynb",
         "getAllCliques": "03_Dataset_Utils.ipynb",
         "clusterByLeidenAlg": "03_Dataset_Utils.ipynb",
         "getOptimalAdjacency": "03_Dataset_Utils.ipynb",
         "addTransformScores": "04_Distribution_Distance_Approaches.ipynb",
         "splitIntoBags": "04_Distribution_Distance_Approaches.ipynb",
         "fitKDE": "04_Distribution_Distance_Approaches.ipynb",
         "KLD": "04_Distribution_Distance_Approaches.ipynb",
         "JSD": "04_Distribution_Distance_Approaches.ipynb",
         "getJSDDistMat": "04_Distribution_Distance_Approaches.ipynb",
         "getKLDMat": "04_Distribution_Distance_Approaches.ipynb",
         "getWassersteinMat": "04_Distribution_Distance_Approaches.ipynb"}

modules = ["data/syntheticData.py",
           "utils.py",
           "distanceApproaches.py"]

doc_url = "https://Dzeiberg.github.io/multiinstance/"

git_url = "https://github.com/Dzeiberg/multiinstance/tree/master/"

def custom_doc_links(name): return None
