# AUTOGENERATED! DO NOT EDIT! File to edit: 17_Tree_Alpha_Estimate_Distrs.ipynb (unless otherwise specified).

__all__ = []

# Cell
import autograd
from autograd import grad,jacobian,hessian
from autograd.scipy import stats as agss
import autograd.numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm
import scipy.stats as ss
import os
from scipy.optimize import minimize
from glob import glob

from .likelihoodMethods import *

import scipy.stats as ss

from .data.syntheticData import buildDataset
from .utils import *
from .agglomerative_clustering import AgglomerativeClustering

os.sched_setaffinity(0,set(range(10,20)))